map $ssl_preread_protocol $edge_stream_http_backend {
  ""      __EDGE_NGINX_HTTP_BACKEND__;
  default __EDGE_SSH_TLS_BACKEND__;
}

map $ssl_preread_alpn_protocols $edge_stream_tls_backend {
  ~*(^|,)(http/1\.1|h2)(,|$) __EDGE_NGINX_TLS_BACKEND__;
  default                    __EDGE_SSH_TLS_BACKEND__;
}

__EDGE_HTTP_STREAM_SERVERS__

__EDGE_TLS_STREAM_SERVERS__
