map $ssl_preread_protocol $edge_stream_http_backend {
  ""      __EDGE_NGINX_HTTP_BACKEND__;
  default __EDGE_SSH_TLS_BACKEND__;
}

map $ssl_preread_alpn_protocols $edge_stream_tls_backend {
  ~*(^|,)(http/1\.1|h2)(,|$) __EDGE_NGINX_TLS_BACKEND__;
  default                    __EDGE_SSH_TLS_BACKEND__;
}

server {
  listen __EDGE_PUBLIC_HTTP_PORT__;
  proxy_pass $edge_stream_http_backend;
  proxy_connect_timeout 10s;
  proxy_timeout 7d;
  ssl_preread on;
}

server {
  listen __EDGE_PUBLIC_TLS_PORT__;
  proxy_pass $edge_stream_tls_backend;
  proxy_connect_timeout 10s;
  proxy_timeout 7d;
  ssl_preread on;
}
