[Service]
# Reset agar tidak ada duplikasi ExecStart dari unit utama
ExecStart=
ExecStartPre=
ExecStart=__XRAY_BIN__ run -confdir __XRAY_CONFDIR__
TimeoutStartSec=90

# Jalankan sebagai user dedicated xray (non-root).
User=xray
Group=xray
DynamicUser=no

ReadWritePaths=/var/log/xray
LogsDirectory=xray
LogsDirectoryMode=0755
