package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNormalizeBlocklistLine(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"ads.example.com":              "ads.example.com",
		"0.0.0.0":                      "",
		"0.0.0.0 tracker.example.net":  "tracker.example.net",
		"0.r.msn.com":                  "0.r.msn.com",
		"||doubleclick.net^":           "doubleclick.net",
		"https://ads.example.org/path": "ads.example.org",
		"@@||allowed.example.com^":     "",
		"localhost":                    "",
	}

	for input, want := range cases {
		if got := normalizeBlocklistLine(input); got != want {
			t.Fatalf("normalizeBlocklistLine(%q) = %q, want %q", input, got, want)
		}
	}
}

func TestReadRenderedBlocklist(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "blocklist.generated.conf")
	content := strings.Join([]string{
		"# generated by adblock-sync",
		"address=/ads.example.com/0.0.0.0",
		"address=/ads.example.com/::",
		"address=/tracker.example.net/0.0.0.0",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("WriteFile() error = %v", err)
	}

	got := readRenderedBlocklist(path)
	want := []string{"ads.example.com", "tracker.example.net"}
	if len(got) != len(want) {
		t.Fatalf("readRenderedBlocklist() len = %d, want %d (%v)", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("readRenderedBlocklist()[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

func TestBuildCustomDatProducesPayload(t *testing.T) {
	t.Parallel()

	payload := buildCustomDat([]string{"ads.example.com", "tracker.example.net"}, "ADBLOCK")
	if len(payload) == 0 {
		t.Fatal("buildCustomDat() returned empty payload")
	}
	if !strings.Contains(string(payload), "ADBLOCK") {
		t.Fatal("buildCustomDat() missing ADBLOCK code marker")
	}
	if !strings.Contains(string(payload), "ads.example.com") {
		t.Fatal("buildCustomDat() missing encoded domain")
	}
}
