# DNS Adblock resolver
port=__ADBLOCK_PORT__
listen-address=127.0.0.1
bind-interfaces
no-resolv
no-hosts
domain-needed
bogus-priv
cache-size=1000
server=__ADBLOCK_UPSTREAM_PRIMARY__
server=__ADBLOCK_UPSTREAM_SECONDARY__
conf-file=__ADBLOCK_RENDERED_FILE__
