port __OPENVPN_PORT_TCP__
proto tcp-server
dev tun
topology subnet
server __OPENVPN_SUBNET_TCP__ __OPENVPN_NETMASK_TCP__
ifconfig-pool-persist __OPENVPN_ROOT__/ipp-tcp.txt
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS __OPENVPN_DNS_PRIMARY__"
push "dhcp-option DNS __OPENVPN_DNS_SECONDARY__"
keepalive 10 60
persist-key
persist-tun
user nobody
group nogroup
script-security 2
ca __OPENVPN_SERVER_DIR__/ca.crt
cert __OPENVPN_SERVER_DIR__/server.crt
key __OPENVPN_SERVER_DIR__/server.key
crl-verify __OPENVPN_SERVER_DIR__/crl.pem
dh none
tls-version-min 1.2
plugin __OPENVPN_AUTH_PAM_PLUGIN__ __OPENVPN_AUTH_PAM_SERVICE__
verify-client-cert none
username-as-common-name
auth SHA256
data-ciphers AES-256-GCM:AES-128-GCM
management __OPENVPN_MANAGEMENT_HOST__ __OPENVPN_MANAGEMENT_PORT__
client-connect "/usr/local/bin/openvpn-connect-guard"
client-disconnect "/usr/local/bin/openvpn-qac-hook disconnect"
status __OPENVPN_ROOT__/status-tcp.log __OPENVPN_STATUS_INTERVAL__
log-append __OPENVPN_ROOT__/server-tcp.log
verb 3
