foreground = yes
setuid = root
setgid = root
pid = /run/stunnel/sshws.pid
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

[sshws]
accept = 127.0.0.1:__SSHWS_STUNNEL_PORT__
connect = 127.0.0.1:__SSHWS_DROPBEAR_PORT__
cert = __CERT_FULLCHAIN__
key = __CERT_PRIVKEY__
client = no
